# Generated by Django 3.2.4 on 2021-07-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('perfume_img', models.CharField(default='', max_length=100)),
                ('color', models.CharField(choices=[('red', 'red'), ('ora', 'orange'), ('yel', 'yellow'), ('gre', 'green'), ('blu', 'blue'), ('pur', 'purple'), ('pin', 'pink'), ('whi', 'white'), ('bla', 'black')], max_length=3)),
                ('time', models.CharField(choices=[('per', '퍼퓸'), ('edp', '오드퍼퓸'), ('edt', '오드뜨왈렛'), ('edc', '오드콜로뉴')], max_length=3)),
                ('love_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('ok_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('hate_count', models.PositiveIntegerField(default=0)),
                ('top', models.CharField(choices=[('CI', 'Citrus fruits'), ('AR', 'Aromatics')], max_length=2)),
                ('middle', models.CharField(choices=[('FL', 'Floral'), ('GR', 'Green'), ('FR', 'Fruity'), ('SP', 'Spices')], max_length=2)),
                ('base', models.CharField(choices=[('WO', 'Wooded'), ('BA', 'Balsamic')], max_length=2)),
            ],
        ),
    ]
