# Generated by Django 3.2.4 on 2021-07-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('perfume_img', models.CharField(max_length=100)),
                ('time', models.CharField(choices=[('per', '퍼퓸'), ('edp', '오드퍼퓸'), ('edt', '오드뜨왈렛'), ('edc', '오드콜로뉴')], max_length=3)),
                ('love_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('ok_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('hate_count', models.PositiveIntegerField(default=0)),
                ('top', models.IntegerField(choices=[(1, 'Citrus fruits'), (2, 'Aromatics')])),
                ('middle', models.IntegerField(choices=[(1, 'Floral'), (2, 'Green'), (3, 'Fruity'), (4, 'Spices')])),
                ('base', models.IntegerField(choices=[(1, 'Wooded'), (2, 'Balsamic')])),
            ],
        ),
    ]
