# Generated by Django 3.2 on 2021-07-23 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gibumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='love_users',
            field=models.ManyToManyField(default='', related_name='love_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
