# Generated by Django 3.2 on 2021-07-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='base',
            field=models.CharField(choices=[('WO', 'Wooded'), ('BA', 'Balsamic')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='perfume',
            name='brand',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='perfume',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfume',
            name='hate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfume',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfume',
            name='love_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfume',
            name='middle',
            field=models.CharField(choices=[('FL', 'Floral'), ('GR', 'Green'), ('FR', 'Fruity'), ('SP', 'Spices')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='perfume',
            name='ok_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfume',
            name='perfume_img',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfume',
            name='time',
            field=models.CharField(choices=[('per', '퍼퓸'), ('edp', '오드퍼퓸'), ('edt', '오드뜨왈렛'), ('edc', '오드콜로뉴')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='perfume',
            name='top',
            field=models.CharField(choices=[('CI', 'Citrus fruits'), ('AR', 'Aromatics')], default='', max_length=2),
        ),
    ]
