# Generated by Django 3.2.4 on 2021-07-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='brand',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='perfume_img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
