# Generated by Django 3.2.4 on 2021-07-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='base',
            new_name='base_group',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='middle',
            new_name='middle_group',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='top',
            new_name='top_group',
        ),
        migrations.AddField(
            model_name='perfume',
            name='base_note',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='perfume',
            name='middle_note',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='perfume',
            name='top_note',
            field=models.CharField(default='', max_length=400),
        ),
    ]
