# Generated by Django 3.2 on 2021-07-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0002_auto_20210724_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='no_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='yes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
