# Generated by Django 3.2 on 2021-08-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0002_community_save_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(null=True, upload_to='gibumeapp/'),
        ),
    ]
