# Generated by Django 3.2.4 on 2021-07-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0002_auto_20210714_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='base',
            field=models.CharField(choices=[('WO', 'Wooded'), ('BA', 'Balsamic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='middle',
            field=models.CharField(choices=[('FL', 'Floral'), ('GR', 'Green'), ('FR', 'Fruity'), ('SP', 'Spices')], max_length=2),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='top',
            field=models.CharField(choices=[('CI', 'Citrus fruits'), ('AR', 'Aromatics')], max_length=2),
        ),
    ]
