# Generated by Django 3.2 on 2021-07-23 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gibumeapp', '0002_perfume_love_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='dislike_users',
            field=models.ManyToManyField(default='', related_name='dislike_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfume',
            name='hate_users',
            field=models.ManyToManyField(default='', related_name='hate_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfume',
            name='ok_users',
            field=models.ManyToManyField(default='', related_name='ok_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
