# Generated by Django 3.2 on 2021-08-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0003_community_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(null=True, upload_to='pjgibume/gibumeapp/'),
        ),
    ]
