# Generated by Django 3.2.4 on 2021-07-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0003_auto_20210726_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=30),
        ),
    ]
