# Generated by Django 3.2 on 2021-07-20 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gibumeapp', '0003_auto_20210720_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='perfume',
            name='like_users',
            field=models.ManyToManyField(default='', related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
