# Generated by Django 3.2 on 2021-07-29 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0004_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='hate_count',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='hate_users',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='love_count',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='love_users',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='ok_count',
        ),
    ]
