# Generated by Django 3.2 on 2021-07-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0004_auto_20210720_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='user',
            new_name='id',
        ),
    ]
