# Generated by Django 3.2 on 2021-08-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0005_auto_20210729_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default='')),
                ('body', models.TextField(default='')),
            ],
        ),
    ]
