# Generated by Django 3.2 on 2021-07-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0005_rename_user_perfume_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user',
        ),
    ]
