# Generated by Django 3.2 on 2021-08-04 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gibumeapp', '0005_alter_community_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='', max_length=20)),
                ('comment_text', models.TextField(default='')),
                ('created_at', models.DateTimeField(default='')),
                ('up_count', models.PositiveIntegerField(default=0)),
                ('down_count', models.PositiveIntegerField(default=0)),
                ('down_users', models.ManyToManyField(blank=True, default='', related_name='down_posts', to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gibumeapp.community')),
                ('up_users', models.ManyToManyField(blank=True, default='', related_name='up_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
