# Generated by Django 3.2 on 2021-08-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0006_communitycomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitycomment',
            old_name='title',
            new_name='post',
        ),
    ]
