# Generated by Django 3.2 on 2021-08-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0007_alter_community_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
