# Generated by Django 3.2 on 2021-08-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gibumeapp', '0009_rename_post_communitycomment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitycomment',
            old_name='title',
            new_name='post',
        ),
    ]
